name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Run lint
        uses: reviewdog/action-golangci-lint@v2

      - name: Run test
        run: make ci

      - name: Run octocov
        uses: k1LoW/octocov-action@v0
